### ISSUE TITLE
Wildcard machtes all folders, not just npm packages

### ISSUE THREAD

**Issue by hanspagel** [stackblitz-labs/pkg.pr.new#116]
Hey, what a great tool! 🌟 We’d like to use it for https://github.com/scalar/scalar, see the PR here: https://github.com/scalar/scalar/pull/2310

We have a bunch of packages, not all are on npm. Some are for Python or other languages. Running `npx pkg-pr-new publish ./packages/*` is super convenient, but it tries to publish non-npm packages, too.

Would be great if we could check the folder for a `package.json` or something.

Failed Run: https://github.com/scalar/scalar/actions/runs/9713285552/job/26809740331

> Error:  ENOENT: no such file or directory, open '/home/runner/work/scalar/scalar/packages/scalar.aspnetcore/package.json'

**Comment by Aslemammad** [comment]
Sure! Let me take a look.

**Comment by Aslemammad** [comment]
Just released pkg-pr-new@0.0.10
