### ISSUE TITLE
Respect monorepo projects

### ISSUE THREAD

**Issue by shimkiv** [stackblitz-labs/pkg.pr.new#119]
Hey Team.
Thank you for this tool!

We have the [o1js](https://github.com/o1-labs/o1js) monorepo projects:

The "o1js" itself with the `package.json` in the root directory:
https://github.com/o1-labs/o1js/blob/647c7e5e55f927737ab854bc92eed9f55bc46a61/package.json#L7-L10:

```json
"repository": {
    "type": "git",
    "url": "https://github.com/o1-labs/o1js.git"
  },
```

And the "mina-signer" project with the `package.json` under the `src/mina-signer` directory:
https://github.com/o1-labs/o1js/blob/647c7e5e55f927737ab854bc92eed9f55bc46a61/src/mina-signer/package.json#L21-L25

```json
"repository": {
    "type": "git",
    "url": "https://github.com/o1-labs/o1js.git",
    "directory": "src/mina-signer"
  },
```

As you can tell, the `mina-signer` one has the `repository` entry of the `package.json` configured with the same Git URL as the `o1js` ([the monorepo style](https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository)) but it also has the  project path descriptor in `repository.directory` property.

If you will take a look at this GH Actions run: https://github.com/o1-labs/o1js/actions/runs/9722423299
then you will notice that published packages have different checksum (and different resulting sizes).
Unfortunately, they both are published with the same name of the main repo project - `o1js`.

Example output.

`mina-signer`:

```shell
Run npx pkg-pr-new publish
  npx pkg-pr-new publish
  shell: /usr/bin/bash -e {0}
shasum for o1js(o1js-1.4.0.tgz): 4eccef1213ed8a0fff476d501ec47928b8d247b1


⚡️ Your npm packages are published.
o1js: npm i https://pkg.pr.new/o1-labs/o1js@4e6b85f
```

`o1js`:

```shell
Run npx pkg-pr-new publish
  npx pkg-pr-new publish
  shell: /usr/bin/bash -e {0}
shasum for o1js(o1js-1.4.0.tgz): e9d579416d420ad3d80af3c8bb0bb5c81fcfb614


⚡️ Your npm packages are published.
o1js: npm i https://pkg.pr.new/o1-labs/o1js@4e6b85f
```

**Comment by shimkiv** [comment]
Ok, works with the "workspaces" :) 

> For workspaces:

**Comment by Aslemammad** [comment]
Thank you so much! happy to see you figured it out!
