### ISSUE TITLE
auto detect npm/pnpm/yarn on PR comment

### ISSUE THREAD

**Issue by himself65** [stackblitz-labs/pkg.pr.new#129]
https://github.com/run-llama/LlamaIndexTS/pull/1005#issuecomment-2202184703

I think the CI bot should detect the workspace package manager

**Comment by AmirSa12** [comment]
Yes, you are right. it should detect the package manager. We will fix this soon!
Thanks for using pkg.pr.new and reporting an issue!

**Comment by Aslemammad** [comment]
to be clear @himself65, where do you want the detected package manager be? is it for the --pnpm argument or you mean the pull request comment pkg.pr.new sends?

**Comment by himself65** [comment]
process.argv0 ? pnpx -> pnpm, npx -> npm...

**Comment by himself65** [comment]
the pull request message, yeah

**Comment by AmirSa12** [comment]
I also assumed you meant the pr message since it is an issue here and must detect the pkg manager.

**Comment by sadeghbarati** [comment]
FYI https://github.com/unjs/nypm

you guys can adopt packageManager detection code from `nypm` if you don't want to add another dependency

**Comment by Aslemammad** [comment]
Thank you so much Sadegh for the suggestion!
