### ISSUE TITLE
Templates cannot be created with `"private": true`

### ISSUE THREAD

**Issue by lachlancollins** [stackblitz-labs/pkg.pr.new#133]
Hi there, I've been adding `pkg-pr-new` to the TanStack projects, and ran across an issue getting templates to work (https://github.com/TanStack/query/pull/7675).

I think the issue relates to #124, which skips private packages, but _also_ skips private templates.

https://github.com/stackblitz-labs/pkg.pr.new/blob/3d23f731370050e5c81206539094965f932cbec8/packages/cli/index.ts#L166-L171

I don't think this is intentional, since the purpose of the `"private"` field is to prevent accidental npm publishing, not to indicate that something should not be importable into a cloud dev environment.

**Comment by Aslemammad** [comment]
That makes total sense, yep!

**Comment by Aslemammad** [comment]
just released 0.0.13, thank you so much!
