### ISSUE TITLE
encountered memory overflow

### ISSUE THREAD

**Issue by Wxh16144** [stackblitz-labs/pkg.pr.new#141]
I am planning to integrate a new project into the library, but during my testing phase on my personal account, I've been consistently facing memory overflow errors.

Here is a brief timeline of what happened:

The last successful build was logged as follows (insert the log here).
When I added two templates, the memory consumption spiked dramatically. Here is the first failure log： [actions log](https://productionresultssa6.blob.core.windows.net/actions-results/cc9ed032-eac0-4c5c-a261-2148bab399c3/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-11T03%3A37%3A06Z&sig=rUhqc3wT14c6yoA2S6yImZECBDBnZZ1qWPAKIh0LuRY%3D&ske=2024-07-11T12%3A34%3A17Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-11T00%3A34%3A17Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-11T03%3A27%3A01Z&sv=2023-11-03)

I then increased the allocated memory to 4GB, but the issue persisted. This is the second failure log ：[actions log](https://productionresultssa18.blob.core.windows.net/actions-results/1c9140bb-3918-4d83-8327-b547101a453a/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-11T03%3A39%3A16Z&sig=pNAr%2FMQKrE0gcSCNlXpqPo9PFDOSGSsXKVLElI9a7WA%3D&ske=2024-07-11T11%3A55%3A04Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-10T23%3A55%3A04Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-11T03%3A29%3A11Z&sv=2023-11-03).

Finally, I bumped up the memory allocation to 8GB, yet the memory overflow occurred again. Here is the most recent failure log [actions log](https://productionresultssa19.blob.core.windows.net/actions-results/e04721be-1daf-4a8f-bc06-a0c500965f3c/workflow-job-run-ca395085-040a-526b-2ce8-bdc85f692774/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-07-11T03%3A38%3A45Z&sig=MLmHmoxxaOU5FDnbFOzuWNmwegQLQTp5XKysU%2B2LjOw%3D&ske=2024-07-11T11%3A48%3A53Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-07-10T23%3A48%3A53Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2023-11-03&sp=r&spr=https&sr=b&st=2024-07-11T03%3A28%3A40Z&sv=2023-11-03)

Thank you for your attention and hard work maintaining this valuable resource.

**Comment by Aslemammad** [comment]
Thank you so much, let me check your PR!
