### ISSUE TITLE
"no workflow defined for ..."

### ISSUE THREAD

**Issue by mmkal** [stackblitz-labs/pkg.pr.new#147]
Hi - this looks great! But I'm trying to run on one of my repos, and getting this hard-to-understand error:

```
{"url":"/check","statusCode":404,"statusMessage":"Not Found","message":"There is no workflow defined for SsowDAxmBD"}
Error: Process completed with exit code 1.
```

Job, although you probably won't have permissions to see the logs: https://github.com/mmkal/trpc-cli/actions/runs/9945221704/job/27474548434

<img width="1364" alt="image" src="https://github.com/user-attachments/assets/bff6d844-d0e1-4263-885e-50f8432df5d3">

Here's the workflow: https://github.com/mmkal/trpc-cli/blob/pkg.pr.new/.github/workflows/pkg.pr.new.yml

Could it be that it's only for looking for GitHub Actions workflows that already exist on `main`? Should I just say yolo and merge anyway?

**Comment by mmkal** [comment]
Had a suspicion that this was something to do with me forgetting to add the app, running the workflow, have it fail, adding the app, then re-running the workflow without pushing a new change.

And that seems to be the case because it worked perfectly when I pushed an unrelated change. Closing, sorry!

**Comment by Aslemammad** [comment]
No issues at all, thank you so much for your help ❤️
