### ISSUE TITLE
Timing out after succesful publish

### ISSUE THREAD

**Issue by wKovacs64** [stackblitz-labs/pkg.pr.new#163]
Hello, and thanks for your efforts on this project - very cool.

I just tried setting this up and for some reason it's timing out after publishing, but only for the pull_request event (the push event from the same commit succeeds). I set this up on another repo previously and it's not happening there.

Here's the PR:

https://github.com/wKovacs64/pwned/pull/279

Any idea what would be causing this?

(Note: I added a timeout after I noticed it running forever so it would fail faster, but you can see a run I manually cancelled after almost 7 minutes [here](https://github.com/wKovacs64/pwned/actions/runs/10124955399).)

**Comment by Aslemammad** [comment]
Thank you so much for the kind words! 

It's getting published but the process does not exit, right? 
![image](https://github.com/user-attachments/assets/41d9fb7a-af46-4d83-8d0d-f71f704cc023)

Can we try removing --yes flag from npm?

**Comment by wKovacs64** [comment]
> It's getting published but the process does not exit, right? 

That's my understanding, yep.

> Can we try removing --yes flag from npx?

Done. Still [hangs after publishing](https://github.com/wKovacs64/pwned/actions/runs/10125296213/job/28000612878?pr=279), though. 😕

**Comment by Aslemammad** [comment]
I'll have a look, thank you for letting me know 🙌

**Comment by Aslemammad** [comment]
I just tried it on my fork and it's working with no issues! 

https://github.com/Aslemammad/pwned/actions/runs/10142824058/job/28043119102#step:7:1

what do you think?

**Comment by wKovacs64** [comment]
> I just tried it on my fork and it's working with no issues!
> 
> https://github.com/Aslemammad/pwned/actions/runs/10142824058/job/28043119102#step:7:1
> 
> what do you think?

Your test is invalid, as the step does exit successfully on `push` events in my repo, too. It's only `pull_request` events that hang. So try opening a PR on your fork I guess.

> Can you try removing the --compact flag too?

Done, no change (still hangs).

**Comment by Aslemammad** [comment]
Ohhh you're right! I forgot that case, I'll try again!

**Comment by Aslemammad** [comment]
Still, it succeed! So I could not reproduce it.

Can you try this command from #166?

`API_URL=https://pkg.pr.new npx pkg-pr-new@https://773145bf.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@166 publish`

What this does is it just exits with process.exit when it finishes processing. 

let me know.

**Comment by wKovacs64** [comment]
That worked! I was able to add `--yes` and `--compact` back in, too (as expected). 👍

**Comment by Aslemammad** [comment]
I appreciate that, let me merge it then!
