### ISSUE TITLE
Support tag for release

### ISSUE THREAD

**Issue by sxzz** [stackblitz-labs/pkg.pr.new#169]
I think it would be great if we could add a tag feature.

With tags like `latest` and `nightly`, I can easily add them to my package. This way, I don’t have to remember each commit and it’s super convenient to use `pr-1000`.

**Comment by Aslemammad** [comment]
I see, do you mean git tags? we can do that easily! 

For instance, https://github.com/stackblitz-labs/pkg.pr.new/tree/v0.0.19 => https://pkg.pr.new/stackblitz-labs/pkg.pr.new/pkg-pr-new@v0.0.19

But right now, you can create branches called latest and nightly, and pkg.pr.new already supports https://pkg.pr.new/stackblitz-labs/pkg.pr.new/pkg-pr-new@main or https://pkg.pr.new/stackblitz-labs/pkg.pr.new/pkg-pr-new@nightly or something like that! What do you think.

**Comment by sxzz** [comment]
It would be better if a `--tag` flag is added to the CLI.

**Comment by Aslemammad** [comment]
I see, so every time a maintainer publishes to that tag, the url with that tag will be updated?

**Comment by Aslemammad** [comment]
Maybe we can name it flags rather than tag, so users won't mistake it with git tags!

**Comment by patak-dev** [comment]
I think that `label` may work better if you want to avoid confusion with git tags. @sxzz curious about your use case. Are these releases going to be issued from `main`? I find that `https://pkg.pr.new/tinybench@main` is a good URL for latest or nightly. At least in Vite, we use main.vitejs.dev for docs tracking the latest in the main branch. Maybe you have other use case in mind? I wonder if `--alias latest` could be another possible naming option for publishing a branch that can be accessed by both its name and another label that has more meaning for the project.

**Comment by sxzz** [comment]
These releases could come from PR, the main branch, or other branches. `alias` is a suitable name.

I hope to access it as follows:
- https://pkg.pr.new/pkg@main
- https://pkg.pr.new/pkg@dev
- https://pkg.pr.new/pkg@pr/123

**Comment by patak-dev** [comment]
These three already works without the alias feature, no? (the last one as `@123`) 
Or you want to be able to access `@main` as `@latest`?

**Comment by Aslemammad** [comment]
@sxzz what do you think of that ☝️?

**Comment by sxzz** [comment]
I tried these links, and they seem to work. That's good enough for me. 👍

**Comment by Aslemammad** [comment]
Amazing! Thank you so much.

**Comment by wmertens** [comment]
@patak-dev We're building the build/v2 branch and this URL works:

https://pkg.pr.new/@qwik.dev/core@6903

but this URL doesn't

https://pkg.pr.new/@qwik.dev/core@v2

Is there a way to make it work?

https://github.com/QwikDev/qwik/pull/6903#issuecomment-2367501204
