### ISSUE TITLE
Support CDN Usage

### ISSUE THREAD

**Issue by sxzz** [stackblitz-labs/pkg.pr.new#170]
I suggest we add a service like unpkg to make it easier to use source files directly in the CDN.

At the same time, it needs to be used together with #169.

**Comment by sxzz** [comment]
The use case is: we can directly load the latest bundle file in the browser.

https://ast.sxzz.moe/#eNqrVspRslIqK01V0lEqgLB0yxIL8ouA/GQgH0jlA6mi1JLSojyF6lqlWgBvbw7g

**Comment by Aslemammad** [comment]
Hmm, what is the usecase of using source files directly?

Don't we most of the times bundle libraries for publishing? And even if we do not, we change the configuration the ship the source files, something like the svelte repo.

**Comment by sadeghbarati** [comment]
@sxzz 

See this [Vue Playground](https://play.vuejs.org/#eNqVlNuO0zAQhl/F5KYgbe0etoCq7qoLWgm4ALQgcROpCsk09a5Psp22osq7M3G6ofSQdu+S+X/PN2OPvYnujKHLAqJxNHGp5cYTB74wt7Hi0mjryYZYmJOSzK2WpIPWzo50l6baZlyrB619Y7JJxtfd2hqrVCvniXQ5ualSve58AiE0+aWtyF513sRqwmoyMvHHgzQi8YB/hEwW/dvNJiwuywnDvxDlyhSeLLtSZyBu4gj1OCIMxQnbWR9dRXWlXZkY+ui0wjY3VYZ4K7g4GpMQqWJN3VU0jhbeGzdmzDzl1FiqYMUax7Q/6L1nGXeecZXBGrPH0dVzoulc6MRzlXcLznCH9hLmCdqNpFwzZeT4wD3t07f0XZ19R6OVRuVpUqbl5SA0B06/dwhCrY1TeC7Czl1GCvZpjw6O9RTEs7CXtXYB8EyHBzPQhgvjQPv0+hCG0j6GKw9WoUOrRPA/kLEMp7WddnzNdEhHdLQdwjDO51mqkL/BvpRWrwq8YRvPrVK2AGHAOjZjs1Qkzs2M5UusdjbnILIZV9y343eS4BmOaH/AwMnT2cLVq0ooY1XilfcOX5w5z/cufKql4QLsN1M19v/FT/BBWn0JMW8LaBpKF5A+HYk/unXdw3cLDuwSj6/RfGJz2LZ4/+MrrPG7EfHBKsT2sE+ID+C0wCHVqrZ9KFSGZe/4QrWfwwHgmP1092sPyj03VRUadiP44whH8GNL6//KHdLrZhfLv9NVEk8=) it uses `pkg.pr.new` links but with main/module field package entry path

---

default `pkg.pr.new` link

```
https://pkg.pr.new/radix-vue@1208
```


modified `pkg.pr.new` link for using inside import maps

```diff
- https://pkg.pr.new/radix-vue@1208
+ https://pkg.pr.new/radix-vue@1208/dist/index.js
```

**Comment by sxzz** [comment]
@Aslemammad In the above AST explorer example, I need to directly reference the latest npm file, such as: https://cdn.jsdelivr.net/npm/@vue-vapor/compiler-vapor/dist/compiler-vapor.esm-browser.js

After switching to pkg.pr.new, is there a similar way?

**Comment by Aslemammad** [comment]
I'm thinking about this, it's a solid use case but it's also out of the scope! Let me see what can I do.

**Comment by Aslemammad** [comment]
I'll close this for now, but @ije might have some suggestions on this.

**Comment by ije** [comment]
i'm think about addding [pkg.pr.new](https://pkg.pr.new) as the **4th** registry of esm.sh:
npm: https://esm.sh/react@18.3.1
jsr: https://esm.sh/jsr/@std/encoding
github: https://esm.sh/gh/ije/md4w
**pr: https://esm.sh/pr/react@a832a55**

@Aslemammad what do you think?

**Comment by Aslemammad** [comment]
Let's do it for sure, and would it support all routes in pkg.pr.new?

And let's have a blog post on the stackblitz blog as an announcement and a collaboration (pkg.pr.new x esm.hs), what do you think?

**Comment by ije** [comment]
> would it support all routes in pkg.pr.new?

i think so! i'm going to test the feasibility.

**Comment by Aslemammad** [comment]
Sure, keep us updated!

**Comment by Aslemammad** [comment]
This is now delivered on https://github.com/esm-dev/esm.sh/pull/904

what do you think @sxzz ?

**Comment by ije** [comment]
you can try it in browser with `next.esm.sh` currently:

```js
import { Bench } from "https://next.esm.sh/pr/tinybench@a832a55"
```

**Comment by sxzz** [comment]
Awesome!

**Comment by sxzz** [comment]
@ije Seems like it can't be resolved: https://next.esm.sh/pr/vuejs/vue-vapor/vue@3f6ce96

**Comment by ije** [comment]
> @ije Seems like it can't be resolved: https://next.esm.sh/pr/vuejs/vue-vapor/vue@3f6ce96

thanks! i will look into it!

**Comment by ije** [comment]
@sxzz fixed!
<img width="543" alt="Screenshot 2024-11-17 at 21 09 56" src="https://github.com/user-attachments/assets/75abd197-a2f2-4882-93a6-51b80ce74a29">
