### ISSUE TITLE
bug: [error] publishing failed

### ISSUE THREAD

**Issue by robingenz** [stackblitz-labs/pkg.pr.new#175]
I am currently trying to integrate pkg.pr.new into my repository, see: https://github.com/capawesome-team/capacitor-plugins/pull/261

Unfortunately, I get the following error message when publishing, see: https://github.com/capawesome-team/capacitor-plugins/actions/runs/10431303133/job/28890904130?pr=261#step:7:105

The GitHub app is installed and has access to the repository:
![grafik](https://github.com/user-attachments/assets/8c8a4bd1-cb9f-41a9-bcc5-d5d2e5fcf6e0)

Any idea what the problem is?

**Comment by Aslemammad** [comment]
Hey, thank you so much for reporting this! 

Do you run the command multiple times? In a workflow, the pkg-pr-new command should run only one time! 

So instead of:
```
pnpm pkg-pr-new './A''
pnpm pkg-pr-new './B'
```

You should do 
```
pnpm pkg-pr-new publish './A' './B'
```

This is so we avoid spam publishes for a single run of a workflow. Let me know if this helps.

**Comment by robingenz** [comment]
Great, thank you! Now it works.

**Comment by Aslemammad** [comment]
Thank you so much, Robin!
