### ISSUE TITLE
Given install command returning `404`

### ISSUE THREAD

**Issue by anikghosh256** [stackblitz-labs/pkg.pr.new#203]
![image](https://github.com/user-attachments/assets/76ec7944-3242-488a-9f76-621c0fb32c38)

The following command, returns a `404 `error, even though it was given by `pkg.pr.new`:

```bash
pnpm add https://pkg.pr.new/sequelize/umzug@678
```

However, the command works when using:
```bash
pnpm add https://pkg.pr.new/sequelize/umzug@a5198db
```

**Comment by Aslemammad** [comment]
Thank you so much for reporting this! 

Do you have any link to the pull request itself? I'd like to investigate it.

**Comment by anikghosh256** [comment]
@Aslemammad [Here](https://github.com/sequelize/umzug/pull/678)

**Comment by Aslemammad** [comment]
Will check soon! Thank you 🙌

**Comment by Aslemammad** [comment]
Ok, I see! 

I think because the PR is created before the installation of the app! 

Can you try another creating another test PR and let me know?
