### ISSUE TITLE
Removing Stackblitz link

### ISSUE THREAD

**Issue by pomber** [stackblitz-labs/pkg.pr.new#208]
I was expecting the `--no-template` flag to remove the `Open in Stackblitz` link from the PR comment, but it isn't happening. 

Is that how it works? 

This is the full command [I'm using](https://github.com/code-hike/codehike/blob/next/package.json#L12):
```
pkg-pr-new publish --no-template --compact './packages/codehike'
```

And here is an [example comment](https://github.com/code-hike/codehike/pull/441#issuecomment-2320804861).

**Comment by Aslemammad** [comment]
Hey, huge fan of your work on codehike, Rodrigo! 

In the next version, this is solved! 

Sorry for the confusion. I'll keep you updated here.

**Comment by pomber** [comment]
thanks! I added pkg.pr.new yesterday and it's already saving me much time.

Will there be a way to customize the comment? I'd love to change it to something like:

````md
Install the version from this pull request in your project with: 

```
npm add https://pkg.pr.new/codehike@441
```
````

**Comment by Aslemammad** [comment]
I appreciate that! 

Yep, we just added #183, you can see the discussion there.

With that, you can create your own comments.

**Comment by Aslemammad** [comment]
btw, if you think you need help with setting it up, I'd be happy to help!

**Comment by Aslemammad** [comment]
I'll close this since I assume it is fixed with the new release. If in any case it was not, please feel free to re-open this.

**Comment by pomber** [comment]
> thanks! I added pkg.pr.new yesterday and it's already saving me much time.
> 
> Will there be a way to customize the comment? I'd love to change it to something like:
> 
> ````
> Install the version from this pull request in your project with: 
> 
> ```
> npm add https://pkg.pr.new/codehike@441
> ```
> ````

@Aslemammad do you have any example of how to do this?

**Comment by Aslemammad** [comment]
```
pnpm pkg-pr-new publish --json=output.json 
```

This would create you an output.json for you with all the built packages and templates.

Then you'd be able to create a script that comments to the current PR that uses `output.json`. In that script, you can format the messages however you want when sending the comment using github api! 

https://github.com/octokit/action.js/
