### ISSUE TITLE
Does it support version replacement for `pnpm workspace`?

### ISSUE THREAD

**Issue by shulaoda** [stackblitz-labs/pkg.pr.new#209]
If I had a pnpm workspace project, the structure would be as follows:
```js
// packages/rolldown
{
  "name": "rolldown",
  "version": "0.12.2",
  "optionalDependencies": {
    "@rolldown/binding-darwin-arm64": "workspace:*",
  }
}

// packages/rolldown/npm/binding-darwin-arm64
{
  "name": "@rolldown/binding-darwin-arm64",
  "version": "0.12.2"
}
```
I execute the following command:
```bash
pnpx pkg-pr-new publish --compact --pnpm './packages/rolldown/npm/*' './packages/rolldown'
```
May I ask if it is possible to support replacing the `@rolldown/binding-darwin-arm64` version `workspace:*` with the URL of `pkg.pr.new` in package `rolldown`?

**Comment by shulaoda** [comment]
Related to https://github.com/rolldown/rolldown/pull/2090

**Comment by Aslemammad** [comment]
Thank you so much, will make a release soon!

**Comment by Aslemammad** [comment]
just released!

**Comment by shulaoda** [comment]
> just released!

Yes, I saw it. Due to some reasons, I will verify it later. Can you tell me the specific usage method?

```bash
pnpx pkg-pr-new publish --compact --pnpm './packages/rolldown/npm/*' './packages/rolldown'
```
or
```bash
pnpx pkg-pr-new publish --compact --pnpm './packages/rolldown'
```

**Comment by Aslemammad** [comment]
> pnpx pkg-pr-new publish --compact --pnpm './packages/rolldown/npm/*' './packages/rolldown'

This, because you need to specify all the packages that are going to be included. And those packages will be replaced if pkg.pr.new sees them in any dependency field.

**Comment by shulaoda** [comment]
> This, because you need to specify all the packages that are going to be included. And those packages will be replaced if pkg.pr.new sees them in any dependency field.

Looks great! Thanks!

**Comment by Aslemammad** [comment]
I appreciate you!
