### ISSUE TITLE
Why am I seeing 400 + "No packages"? (regression)

### ISSUE THREAD

**Issue by webpro** [stackblitz-labs/pkg.pr.new#212]
To me it seems things are set up properly (app installed, `package.json#repository` set, workflow added), but I'm running into this issue:

- Failing task: https://github.com/webpro/reveal-md/actions/runs/10645943580/job/29512256471#step:4:5
- Exception thrown at: https://github.com/stackblitz-labs/pkg.pr.new/blob/44fa427c4e2533ef26c81bac82fee906c015af94/packages/backend/server/routes/publish.post.ts#L59-L70

Output:

```
Run npx --yes pkg-pr-new publish
  npx --yes pkg-pr-new publish
  shell: /usr/bin/bash -e {0}
Error:  publishing failed: {"url":"/publish","statusCode":400,"statusMessage":"","message":"No packages"}
  at Object.run (/home/runner/.npm/_npx/e8f433c388b218fc/node_modules/pkg-pr-new/dist/index.js:3326:18)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async runCommand (/home/runner/.npm/_npx/e8f433c388b218fc/node_modules/pkg-pr-new/dist/index.js:2196:16)
  at async runCommand (/home/runner/.npm/_npx/e8f433c388b218fc/node_modules/pkg-pr-new/dist/index.js:2187:11)
  at async runMain (/home/runner/.npm/_npx/e8f433c388b218fc/node_modules/pkg-pr-new/dist/index.js:2323:7)
```

Looking back, here's a successful run, but has an error too:

https://github.com/webpro/reveal-md/actions/runs/9888941492/job/27313935552

Any chance you could see what I'm doing wrong? Or maybe it's a bug in pkg.pr.new?

Either way, there's room for improvement. Let me know if you need more details.

**Comment by Aslemammad** [comment]
Hey, thank you for reporting this! 

That's weird, sorry for that! Can you remove --yes and let me know?

**Comment by Aslemammad** [comment]
Or can you try a previous version of pkg.pr.new? 

`npx pkg.pr.new@version publish`?

**Comment by webpro** [comment]
Seems like the issue is introduced in v0.0.21 for me: https://github.com/webpro/reveal-md/actions (v0.0.20 seems fine).

(That `--yes` is just saying to npx it can go download the package, which is the default, `--no-install` is the opposite, but removed it for now.

**Comment by webpro** [comment]
Btw no worries please don't prioritize if it seems to hit just me.

**Comment by enzonotario** [comment]
I'm also having this issue in: https://github.com/enzonotario/vitepress-theme-openapi/actions/runs/10646338885

**Comment by Aslemammad** [comment]
Ok I'll just resolve it, sorry for the bad experience!

Thank you.1

**Comment by Aslemammad** [comment]
will make a release soon (0.0.23)! 

Feel free to re-open if the issue seems to persist!

**Comment by Aslemammad** [comment]
I think the release is available, let me know what you think!

**Comment by webpro** [comment]
All good! Thanks a bunch @Aslemammad, good stuff.

**Comment by Aslemammad** [comment]
❤️

**Comment by enzonotario** [comment]
@Aslemammad I'm still seeing this issue.. or am I doing something wrong?

https://github.com/enzonotario/vitepress-theme-openapi/actions/runs/10658192900/job/29538896357?pr=27#step:6:11

thanks in advance!

**Comment by Aslemammad** [comment]
Oh I see an edge case, will do something for this! 

The issue comes from tinyglobby which is not good with`.` paths apparently. That was the whole bug and it's apparent again if the user specifies it.

Let me tag @SuperchupuDev.

**Comment by SuperchupuDev** [comment]
interesting, what is the pattern that isn't working?

**Comment by Aslemammad** [comment]
`.` and `./`!

**Comment by Aslemammad** [comment]
See #214

**Comment by SuperchupuDev** [comment]
sadly it looks like this is an fdir limitation (the dir walker library tinyglobby uses), but i can pr a workaround to this project meanwhile

**Comment by SuperchupuDev** [comment]
opened #218 👀

**Comment by Aslemammad** [comment]
@enzonotario Can you try this command and see if it works now?

```sh
pnpm dlx pkg-pr-new@https://dbabc425.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@6d836ce publish --compact --pnpm ./
```

**Comment by enzonotario** [comment]
@Aslemammad sorry but how should I try this?

I edited it in my Workflow file, but I see this error: https://github.com/enzonotario/vitepress-theme-openapi/actions/runs/10667042043/job/29563770522?pr=28#step:6:12

I also tried to run it in my Local, but it says `Continuous Releases are only available in Github Actions.`

**Comment by Aslemammad** [comment]
> I edited it in my Workflow file, but I see this error: https://github.com/enzonotario/vitepress-theme-openapi/actions/runs/10667042043/job/29563770522?pr=28#step:6:12

Sorry, this is correct! Can you add this env variable too? `API_URL=https://pkg.pr.new`

**Comment by enzonotario** [comment]
Yes! It's now working fine (https://github.com/enzonotario/vitepress-theme-openapi/actions/runs/10667234045/job/29564363431#step:6:17)

I'll wait for a release. Thanks so much!

**Comment by Aslemammad** [comment]
Amazing, we'll do a release! Thank you so much.

**Comment by Aslemammad** [comment]
Just sent a release! Thank you so much again ❤️
