### ISSUE TITLE
Files within folders of templates are URL encoded

### ISSUE THREAD

**Issue by nerdyman** [stackblitz-labs/pkg.pr.new#229]
Hi, I've recently set up the GitHub bot in one of my repos. The package publishing is working but nested files in the folder I'm using for the `--template` arg are being URL encoded, causing the file structure to be flatened.

Here's a [link to the bot comment](https://github.com/nerdyman/react-compare-slider/pull/143#issuecomment-2335165148) and the [Stackblitz project it created](https://stackblitz.com/run?file=README.md).

<img width="253" alt="Flattened file structure" src="https://github.com/user-attachments/assets/c51a68a8-3417-4495-aec7-bc848ecfac7c">

The `/` in the file paths has been escaped so the files don't resolve.

---

P.S. really loving the simplicity of this plugin! It's way nicer than publishing pre-releases to npm.

**Comment by Aslemammad** [comment]
Thank you for the kind words! 

Oh, that's bad! Let me think and find a solution with the team!

**Comment by Aslemammad** [comment]
Hey @nerdyman 

Can you try this command in your workflow and see if now it solves your issue?

```
API_URL=https://pkg.pr.new pnpx pkg-pr-new@https://be6db5b4.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@236 publish './lib' # and all the options you want...
```

**Comment by nerdyman** [comment]
@Aslemammad That didn't work for me either unfortunately, the file paths are still escaped.

I used

```sh
API_URL=https://pkg.pr.new/ pnpx pkg-pr-new@https://be6db5b4.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/pkg-pr-new@236 publish './lib' --template='./docs/example'
```

https://github.com/nerdyman/react-compare-slider/actions/runs/10836757398/job/30071202990?pr=143#step:7:1

I'm not sure if https://github.com/stackblitz-labs/pkg.pr.new/pull/236 would resolve the issue completely though. It looks like it will escape `[` and `]` but frameworks like Next.js use square brackets in file names so files like `[...nextauth].ts` would still be escaped.

**Comment by Aslemammad** [comment]
I see, I guess that's because it uses the old backend and not the updated one! Can you folks give me the repo you're trying pkg.pr.new on, so I fork it and try it?

And `[]` has to be escaped because otherwise it'd fail, but I guess it'd work, let's see what happens with the repros.

**Comment by Aslemammad** [comment]
I'm testing it on the PR, let's see how it goes!

**Comment by Aslemammad** [comment]
Ok, as you can see in the PR (example-2), it is working. Sorry for the confusion. 

Will ship it soon.
