### ISSUE TITLE
Weird install preview message in a yarn repo

### ISSUE THREAD

**Issue by phryneas** [stackblitz-labs/pkg.pr.new#230]
Just wanteds to report his as I'm trying this tool out right now - something is wrong with the comment:

See https://github.com/phryneas/remark-typescript-tools/pull/15#issuecomment-2336716697

![grafik](https://github.com/user-attachments/assets/02b998cd-5e6a-46e7-89e1-77c6657307a5)

**Comment by Aslemammad** [comment]
Oh

What do you think @brc-dd ?
