### ISSUE TITLE
Information from the `continuous-releases-staging bot` can be processed again in the action

### ISSUE THREAD

**Issue by RSS1102** [stackblitz-labs/pkg.pr.new#231]
I want to have a requirement that I want to implement through pkg.pr.new. When I want to fix one or more issues through a pr, I want to send comments on the `continuous-releases-staging bot`'s information to all issues mentioned in this pr after the pr merge, not just the current pr.

**Comment by Aslemammad** [comment]
That's a bit out of scope!

Maybe you can create your own script and that! Using the --json option in
pkg.pr.new

**Comment by Aslemammad** [comment]
feel free to re-open!
