### ISSUE TITLE
The app is not installed

### ISSUE THREAD

**Issue by shulaoda** [stackblitz-labs/pkg.pr.new#233]
I have encountered some other issues, could you help me take a look? @Aslemammad 

Actually, we have already installed it. 

Related to https://github.com/web-infra-dev/rspack/pull/7757

```bash
Run pnpm run test:pkg

> monorepo@1.0.3 test:pkg /home/runner/work/rspack/rspack
> pnpm exec pkg-pr-new publish --compact --pnpm './npm/*' './crates/node_binding' './packages/rspack'

{"url":"/check","statusCode":404,"statusMessage":"Not Found","message":"The app https://github.com/apps/pkg-pr-new is not installed on web-infra-dev/rspack."}
 ELIFECYCLE  Command failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by Aslemammad** [comment]
Oh I see, can you try installing it on the specific repo instead of the whole organization and let me know? Just to verify my assumptions so I fix it for you somehow.

**Comment by Aslemammad** [comment]
Oh wait don't, I'll fix it and let you know 😅

**Comment by Aslemammad** [comment]
ok can you try this

```
API_URL=https://pkg.pr.new pnpm dlx pkg-pr-new@https://7b32ad52.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/playground-b@234 publish --compact --pnpm './npm/*' './crates/node_binding' './packages/rspack'
```

And let me know?

**Comment by shulaoda** [comment]
> ok can you try this
> 
> ```
> API_URL=https://pkg.pr.new pnpm dlx pkg-pr-new@https://7b32ad52.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/playground-b@234 publish --compact --pnpm './npm/*' './crates/node_binding' './packages/rspack'
> ```
> 
> And let me know?

Sure, wait a moment.

**Comment by shulaoda** [comment]
Great! @Aslemammad

**Comment by Aslemammad** [comment]
Will ship it soon!
