### ISSUE TITLE
Templates broke in a weird way 

### ISSUE THREAD

**Issue by markflorkowski** [stackblitz-labs/pkg.pr.new#243]
It seems like file paths are being url encoded, which totally breaks the environment. 

![image](https://github.com/user-attachments/assets/b8af287b-484e-47e2-b4fc-4339145b7cbd)

Here's my action yaml:
https://github.com/pingdotgg/uploadthing/blob/main/.github/workflows/pkg-pr-new.yaml

Here's some examples"
- [@example/minimal-appdir](https://pkg.pr.new/template/908d0fa6-bac6-45e1-867d-2c37e74377e9)
- [@example/minimal-astro-react](https://pkg.pr.new/template/f5cc71e2-17b7-479e-8c17-36a048056fb9)
- [@example/minimal-expo](https://pkg.pr.new/template/3bc17aac-8bc9-446c-a5a2-7c5157275c76)
- [@example/minimal-nuxt](https://pkg.pr.new/template/d9ae6521-e2a0-44f0-930c-4ea42187a858)
- [@example/minimal-pagedir](https://pkg.pr.new/template/ec540a2c-5491-4503-b7e8-bc786a713bf9)
- [@example/minimal-solidstart](https://pkg.pr.new/template/70635cd6-9779-4105-abf6-fa5a3126b719)
- [@example/minimal-sveltekit](https://pkg.pr.new/template/00bce698-09be-4bdb-9cf0-32f38ddc3edb)

**Comment by Aslemammad** [comment]
Sorry for the bad experience, I'll make a release for https://github.com/stackblitz-labs/pkg.pr.new/commit/353c98865d449c912f1d53ae4194957ea3712c46 and let me know if it works for you.

**Comment by Aslemammad** [comment]
we released 0.0.25! Let me know if it solves the issue for you.

**Comment by Aslemammad** [comment]
i guess we can close this for now, feel free to re-open!
