### ISSUE TITLE
CLI and server should check the version from the branch

### ISSUE THREAD

**Issue by userquin** [stackblitz-labs/pkg.pr.new#244]
We've a problem when moving https://github.com/nuxt-modules/i18n main branch for new `alpha-9` version.

The repo was using old Nuxt comminuty links, and so latest stable version (8.5.4) on npm registry using `nuxt-community` instead `nuxt-modules`.

When publishing, the CLI will work, but the `pkg-pr-new` will redirect using data from wrong version (since it uses the old latest version from the registry).

You can check the link here: https://github.com/nuxt-modules/i18n/actions/runs/10972498978/job/30468861871

<details>
<summary>Release with pkg-pr-new</summary>

![imagen](https://github.com/user-attachments/assets/0716eda0-8c0b-48cb-b8b2-eb5e3ad836e2)
</details>

<details>
<summary>pkg-pr-new server redirection opening link from previous Release with pkg-pr-new link</summary>

![imagen](https://github.com/user-attachments/assets/c1ad8e12-898b-4ead-b9ad-e65c1f30e79a)
</details>

**Alternatives**: for the i18n nuxt module we can release a patch version to update the repo link.

**Comment by Aslemammad** [comment]
The link works for me, can you try again? I guess it's because you updated the repository field in the package.json and published it on github, so now pkg.pr.new resolves to the right repo.

**Comment by userquin** [comment]
because we released a patch for latest version (v8.5.5)

**Comment by Aslemammad** [comment]
Amazing, if it now works for you, we can close this issue. feel free to.
