### ISSUE TITLE
Error:  File is not defined

### ISSUE THREAD

**Issue by afc163** [stackblitz-labs/pkg.pr.new#245]
https://github.com/ant-design/ant-design/actions/runs/11027020209/job/30624890296

<img width="870" alt="image" src="https://github.com/user-attachments/assets/c62e489e-ef40-46b7-876b-653f30ce447c">

**Comment by pnodet** [comment]
Running into the same issue: https://github.com/nivalis-studio/nivalis-std/actions/runs/11029726871/job/30632783482

<img width="1105" alt="Screenshot 2024-09-25 at 11 06 08" src="https://github.com/user-attachments/assets/5cc653ae-c9b8-42de-bc16-dbeeb147fe23">

**Comment by Aslemammad** [comment]
Sorry for this, let me see the issue!

**Comment by o-az** [comment]
last release broken for me too can confirm

**Comment by Aslemammad** [comment]
Let me do a release asap!

**Comment by pnodet** [comment]
fixed! thanks for the quick response
