### ISSUE TITLE
500 errors due to "cannot read properties of undefined (reading 'owner')"

### ISSUE THREAD

**Issue by SokratisVidros** [stackblitz-labs/pkg.pr.new#247]
Hi there,

We recently added [preview deployments for Novu NPM packages](https://github.com/novuhq/novu/blob/next/.github/workflows/release-packages-preview.yml). However, we often get these 500 errors due to a "cannot read properties of undefined (reading 'owner')" error. For example, you can see this [workflow run](https://cloud.nx.app/runs/EEEJk1HJCY).

**Our setup**

The `packages` folder in our NX-powered mono repo contains 14 packages. On every PR, we use `nx affected` to see which packages changed between our trunk (`next`) branch and the current PR HEAD. The affected packages are then deployed as preview packages. 

The packages depend on each other. Every package depends on the `@novu/shared` package. As you can see, in the failed run, some packages fail due to the undefined 'owner' error and others due to a 404 no workflow error. The PR that triggered the failed run only touches the `@novu/shared` package.

**Stacktrace**

```Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +53
+++++++++++++++++++++++++++++++++++++++++++++++++++++
Progress: resolved 53, reused 53, downloaded 0, added 53, done
shasum for @novu/framework(novu-framework-2.1.0.tgz): e4ca8513eb3401b73584af3dae474c1164db8850
[error] publishing failed: {"url":"/publish","statusCode":500,"statusMessage":"","message":"Cannot read properties of undefined (reading 'owner')"}
  at Object.run (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/19229b4f4f8-1418/node_modules/.pnpm/pkg-pr-new@0.0.27/node_modules/pkg-pr-new/dist/index.js:3414:18)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async runCommand (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/19229b4f4f8-1418/node_modules/.pnpm/pkg-pr-new@0.0.27/node_modules/pkg-pr-new/dist/index.js:2196:16)
  at async runCommand (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/19229b4f4f8-1418/node_modules/.pnpm/pkg-pr-new@0.0.27/node_modules/pkg-pr-new/dist/index.js:2187:11)
  at async runMain (/home/runner/.cache/pnpm/dlx/t6c2gbxqvfjjki5ut3q3wgvbcu/19229b4f4f8-1418/node_modules/.pnpm/pkg-pr-new@0.0.27/node_modules/pkg-pr-new/dist/index.js:2323:7) 

[error] publishing failed: {"url":"/publish","statusCode":500,"statusMessage":"","message":"Cannot read properties of undefined (reading 'owner')"}```

Can you please help us identify the issue of this failure?

Thank you in advance.

**Comment by Aslemammad** [comment]
Hey! I'll check it soon and resolve it for you!

**Comment by Aslemammad** [comment]
Interesting, the error is pretty vague, so hopefully #248 would fix it.

Regarding the cause of the error, I see this:
![image](https://github.com/user-attachments/assets/961370b1-9c58-47ca-81ef-7af3d3a6688d)

In a github workflow run, you cannot run a pkg.pr.new command multiple times since there's a hash created in our server that would be consumed after the first run. That's why it gives cannot read from undefined, since the workflow gets removed after the first run (to avoid spam and clean up space).

Here's the right approach: 

`pnpm pkg-pr-new publish './packages/changed-A' './packages/changed-B'`

You should put all the changed packages in the same command, rather than running pkg.pr.new for each changed package. 

Let me know if it makes sense to you.

**Comment by SokratisVidros** [comment]
Thanks @Aslemammad. This is helpful. Is it possible to specify package names instead of folders?

**Comment by SokratisVidros** [comment]
I now get a 400 No package error. See [here](https://github.com/novuhq/novu/actions/runs/11078665094/job/30786384868?pr=6586).

The command that is executed is the following: ```pnpx pkg-pr-new publish './packages/cli' './packages/client' './packages/framework' './packages/headless' './packages/js' './packages/nest' './packages/node' './packages/notification-center' './packages/providers' './packages/react' './packages/shared' './packages/stateless'```

**Comment by Aslemammad** [comment]
Hmm, interesting! 

The escaping looks weird, can't we have something like the command you sent?

![image](https://github.com/user-attachments/assets/3211cf53-2a70-4c7c-965d-e7180931e716)

**Comment by SokratisVidros** [comment]
The original command is `pnpx pkg-pr-new publish './packages/cli' './packages/client' './packages/framework' './packages/headless' './packages/js' './packages/nest' './packages/node' './packages/notification-center' './packages/providers' './packages/react' './packages/shared' './packages/stateless'`. The scripts that generates it is [here](https://github.com/novuhq/novu/pull/6586/files#diff-01c361402d512b3a38f2be9b6430b3d75a1f09754483a38e5d5876a21bca87efR60).

Maybe it's an `execa` glitch. Execa escapes quotes on console.error

**Comment by Aslemammad** [comment]
I see, is it possible that the cwd the execa running in might not be the right place? 

because if those items are right, then the only way they might not resolve is that they might not be there. 

I guess the cwd or the path the command runs in might not be the right place!

**Comment by SokratisVidros** [comment]
It was an escaping issue after all. Thanks for the help. The project rocks!

**Comment by Aslemammad** [comment]
Amazing to see it works, thank you so much.
