### ISSUE TITLE
Add docs about the usage of `--json` flag

### ISSUE THREAD

**Issue by David-Pena** [stackblitz-labs/pkg.pr.new#252]
It was mentioned in [X's post](https://x.com/asleMammadam/status/1840490250319298751) that with this flag, you can output the results in the command line or to a file, but there are no details about this in the docs.

I and multiple other newbies to GitHub Actions would appreciate if this were added 🙌 ♥️

**Comment by Aslemammad** [comment]
We just landed this in #262
