### ISSUE TITLE
Add example with custom comment in the README

### ISSUE THREAD

**Issue by David-Pena** [stackblitz-labs/pkg.pr.new#253]
I'd like to add/show a custom comment with the action details

Something like "_If you can't wait the official release, you can try this out right now!_" plus the details⬇️
![image](https://github.com/user-attachments/assets/640b29a1-ff78-4577-a2b9-0237d95645ee)

It was mentioned in [X's post](https://x.com/Unans___/status/1840511735716884838) that this is possible using the `comments` flag and some triggering workflow (I'm quite lost in here 🤔). It would be awesome to have an example like this added to the docs and so many users would appreciate it 🙌

**Comment by Aslemammad** [comment]
We just landed this in #262

**Comment by David-Pena** [comment]
Excited to try it out tomorrow 🧑🏼‍💻
