### ISSUE TITLE
Idea: customize install command in GH App

### ISSUE THREAD

**Issue by webpro** [stackblitz-labs/pkg.pr.new#260]
Example output of the GH App:

```
⚡️ Your npm packages are published.
knip: npm i https://pkg.pr.new/knip@d9ae5dc
```

This is a command I often copy-paste, so with this in mind two ideas here:

- Ability to add `-D` or `--save-dev` for when the lib is a dev dep
- Extending this idea, not necessarily a fan myself, people could prefer to swap `npm i` for [`ni`](https://github.com/antfu-collective/ni) or `pnpm add` etc.

WDYT?

**Comment by webpro** [comment]
By the way, kinda surprised to see it uses Yarn in the message like here: https://github.com/release-it/conventional-changelog/pull/100#issuecomment-2395484076

**Comment by Aslemammad** [comment]
Hey, we're working on this to see what we can come up with, sorry for the late response! 

Around the message, do you mean the .tgz at the end? if yes, as far as i know, yarn needs that for urls. If it does not need it anymore, we can just remove it. Let me know.

**Comment by webpro** [comment]
> Hey, we're working on this to see what we can come up with, sorry for the late response!

No worries, just spitting out ideas and feedback, hope you don't mind! This project's such a productivity win, it's incredible.

> Around the message, do you mean the .tgz at the end? if yes, as far as i know, yarn needs that for urls. If it does not need it anymore, we can just remove it. Let me know.

Guess it's just my pet peeve but what I meant is usage of `yarn` itself. I believe it isn't de facto standard, and everyone not using `npm` knows how to translate any command. That's why I thought it's a bit odd to print a command with Yarn without knowing the package manager for the repo that's using the pkg-pr-new GH App.

**Comment by Aslemammad** [comment]
> No worries, just spitting out ideas and feedback, hope you don't mind! This project's such a productivity win, it's incredible.

That's for sure, just feel free to share more, happy to discuss anything.

> That's why I thought it's a bit odd to print a command with Yarn without knowing the package manager for the repo that's using the pkg-pr-new GH App.

Oh I see, we have a detect package manager that detects it since users wanted that, but I guess it does not work for you, because your workspace does not use yarn, correct?

**Comment by webpro** [comment]
> Oh I see, we have a detect package manager that detects it since users wanted that, but I guess it does not work for you, because your workspace does not use yarn, correct?

Correct! It's a repo without a lockfile checked in so I'd suspect the default/fallback is Yarn.

**Comment by Aslemammad** [comment]
We just landed a recipe in #262, it'd teach how you can achieve fully customizable comments thanks to @AmirSa12

**Comment by webpro** [comment]
Thank you!

**Comment by Aslemammad** [comment]
You're welcome ❤️
