### ISSUE TITLE
Dependent packages in a monorepo

### ISSUE THREAD

**Issue by hemandev** [stackblitz-labs/pkg.pr.new#261]
Hi,

I am using pnpm workspaces with multiple packages that have dependencies on each other.

For example:

**Package A** - `package.json`

```json
{
  "dependencies": {
    "packageB": "v1.2.3"
  }
}
```

If I change both **Package A** and **Package B**, I want the package created for **Package A** to also use the updated version of **Package B**.

The package.json of A should like 
```json
{
  "dependencies": {
    "packageB": "https://pkg.pr.new/Engagespot/engagespot-core/@engagespot/packageB@c091b44"
  }
}
```
Would it be possible to do achieve this ?
Thanks!

**Comment by Aslemammad** [comment]
Thank you so much for asking.

if you do `pnpm pkg-pr-new publish ./packages/packageA ./packages/packageB` this would be achieved.

**Comment by hemandev** [comment]
It's working, thank you for the quick response!

**Comment by Aslemammad** [comment]
thank you so much!
