### ISSUE TITLE
Use npm in the bot comment by default

### ISSUE THREAD

**Issue by kettanaito** [stackblitz-labs/pkg.pr.new#268]
It would be great to use `npm i` in the bot comment by default. 

I believe the tool tries to figure out what package manager I'm using, and uses that:

<img width="938" alt="Screenshot 2024-10-27 at 12 32 20" src="https://github.com/user-attachments/assets/62bc5ffa-2431-41f3-85a9-dcf0f8f05978">

While this is great for me, the maintainer, it's not so great for other folks, who are the target audience for these granular releases. 

Using `npm` is a safer option. Folks using custom package managers know how to extrapolate from npm commands. Folks who don't use custom managers will be confused seeing pnpm/yarn/etc.

**Comment by AmirSa12** [comment]
Thank you so much for the feedback! 
What do you think about using a custom message instead of this default comment? We have a `--json` option that allows you to generate custom messages and have more control over the content:
[Custom GitHub Messages and Comments](https://github.com/stackblitz-labs/pkg.pr.new?tab=readme-ov-file#custom-github-messages-and-comments).

**Comment by Aslemammad** [comment]
Yea, if Artem likes --json comments, then let's stick to that, but if having an option like `--no-detect` or something like that (feel free to suggest a name) would work, then let's have that too. let us know.

**Comment by kettanaito** [comment]
@AmirSa12, that's a good alternative but a bit verbose. I'd argue that detecting the package manager based on the repo is unexpected here because the target audience for preview releases isn't the maintainers. I can build any version of my library at any time, linking and all, but for others that's a trickier task. With the user's best interests in mind, npm must be the default, if not the only option. 

@Aslemammad, if you want to keep autodetecting, how about `--package-manager=XYZ` to explicitly use the manager specified? I could then use `--package-manager=npm` because that makes most sense for me.

**Comment by Aslemammad** [comment]
what do you think about `--no-detection`?

**Comment by kettanaito** [comment]
@Aslemammad, I think it needs context to be understood. Detection of what? It assumes I know this package does the package manager detection (which I didn't know). And even if I understand that, what package manager would be used then if I disable this detection? 

Overall, it's too implicit to my liking. I prefer `--package-manager=XYZ`, as in "I want to use XYZ package manager with `pkg.pr.new`. Explicit and clear.

**Comment by Aslemammad** [comment]
ok that makes more sense, we will tackle it soon!

**Comment by kettanaito** [comment]
🎉 Amazing.
