### ISSUE TITLE
Why does this not publish PR packages?

### ISSUE THREAD

**Issue by wmertens** [stackblitz-labs/pkg.pr.new#270]
We have [a PR that tracks our v2 branch](https://github.com/QwikDev/qwik/pull/6903) (`build/v2`), but it doesn't get the PR comment, and the release process makes packages based on the commitish and not the PR number, e.g.

https://github.com/QwikDev/qwik/actions/runs/11426278674/job/31789216913#step:13:26

Can I somehow convince it to use the @6903 tag?

**Comment by AmirSa12** [comment]
Thanks for reporting!
As I looked over the PR, I could see the comment which uses the PR number (6903) here: https://github.com/QwikDev/qwik/pull/6903#issuecomment-2367501204
And also gets updated with the latest commit.
Is this what you are expecting?

**Comment by wmertens** [comment]
Oh my :flushed: I totally missed that between all those commits :sweat_smile:

Thank you! I'll close this now.
