### ISSUE TITLE
How to clear cache and install latest version 

### ISSUE THREAD

**Issue by theoephraim** [stackblitz-labs/pkg.pr.new#281]
Not a problem with this tool, but wondering if you folks may know the answer as it is very much related to using preview releases from pkg.pr.new

When installing packages from tarballs, pnpm likes to use its cache - and while the PR preview url may remain static, the contents may be changing as I keep iterating on an open PR. While you can clear the _entire_ cache and reinstall everything, I'd like to just tell it to force a reinstall of the latest tarball found at the url, ignoring the local cache.

I've posted the question on pnpm repo [here](https://github.com/orgs/pnpm/discussions/8568) but got no response.

I've run into the same issue with yarn.

Thank you!

**Comment by Aslemammad** [comment]
Hey, thank you so much for asking! yep, that's unfortunate.  

I think a while ago we had this on #235 and it should work with `-f` option when installing a specific tarball. Let me know.

**Comment by theoephraim** [comment]
Added some more info on the [pnpm discussion](https://github.com/orgs/pnpm/discussions/8568). Seems there is no way to do it. Checked yarn and it seems we have a similar situation. Did not check npm yet.

Only 2 workarounds at the moment:
- clear the entire cache and reinstall (yuck)
- install at specific commit hashes instead of PR numbers

Really not ideal. Should probably add some info in the readme, and encourage/help pnpm + yarn to fix the situation.

**Comment by Aslemammad** [comment]
Nice! Thank you so much for the catch. I love the solution of encouraging them to disable cache on urls or at least check some kind of header first!

**Comment by Aslemammad** [comment]
this was just fixed in pnpm! https://github.com/pnpm/pnpm/issues/8833

**Comment by theoephraim** [comment]
🥳 Thanks!!

**Comment by Aslemammad** [comment]
i wish you had x/bsky! 

https://x.com/asleMammadam/status/1867220072177250750
https://bsky.app/profile/aslemammad.bsky.social/post/3ld4jofdix22l

**Comment by theoephraim** [comment]
Haven't really started using it yet, but my username is @theozero.bsky.social
