### ISSUE TITLE
Is it possible to auto install the package in templates?

### ISSUE THREAD

**Issue by ieedan** [stackblitz-labs/pkg.pr.new#285]
Right now if I have a custom template the package does not come auto installed. The default template has this behavior but from what I can tell it doesn't exist for custom templates. 

It would be nice if the package could come auto installed on the project even if not by default through a flag or something.

**Comment by Aslemammad** [comment]
hey, thank you for creating an issue. this makes sense, but i do not think it would be the expected behaviour. 

the package should be first installed by the maintainer itself, then pkg.pr.new would scan the package.json and replace the old value with the newly generated link.

**Comment by ieedan** [comment]
> hey, thank you for creating an issue. this makes sense, but i do not think it would be the expected behavior. 
> 
> 
> 
> the package should be first installed by the maintainer itself, then pkg.pr.new would scan the package.json and replace the old value with the newly generated link.  

Yeah that makes sense is that the way it currently works or just thoughts on implementation?

**Comment by ieedan** [comment]
> hey, thank you for creating an issue. this makes sense, but i do not think it would be the expected behavior. 
> 
> 
> 
> the package should be first installed by the maintainer itself, then pkg.pr.new would scan the package.json and replace the old value with the newly generated link.  

Yeah that makes sense is that the way it currently works or just thoughts on implementation?

**Comment by ieedan** [comment]
Ah yeah I see now.

Is this documented somewhere and I just missed it?

**Comment by Aslemammad** [comment]
that is the way it works right now! 

And no, we did not document it :) thought it's just the expected behavior.

**Comment by ieedan** [comment]
> that is the way it works right now!
> 
> And no, we did not document it :) thought it's just the expected behavior.

It's definitely a nice behavior I guess maybe it would be expected if I knew more about stackblitz. Thanks!

**Comment by Aslemammad** [comment]
thank you so much for closing the issue, haha, no issues at all, let me know if you need anything and i'll try my best to handle it for you!
