### ISSUE TITLE
Error `No authorization header was set for the request.` on install

### ISSUE THREAD

**Issue by AriPerkkio** [stackblitz-labs/pkg.pr.new#290]
I'm seeing following error when trying to install freshly published packages.

```sh
$ pnpm i https://pkg.pr.new/@tutorialkit/react@422
 ERR_PNPM_FETCH_404  GET https://pkg.pr.new/@tutorialkit/react@422: Not Found - 404

This error happened while installing a direct dependency of /x/y/z/repros/empty

No authorization header was set for the request.
```

https://github.com/stackblitz/tutorialkit/pull/422#issuecomment-2497335370

**Comment by Aslemammad** [comment]
just working on it!

**Comment by Aslemammad** [comment]
we'll have a release asap! sorry for taking long, the bug was from somewhere else.

**Comment by AriPerkkio** [comment]
Packages install now without any erorrs, thanks @Aslemammad! 💯
