### ISSUE TITLE
Getting a 404 on install

### ISSUE THREAD

**Issue by franky47** [stackblitz-labs/pkg.pr.new#299]
My experience with pkg.pr.new is usually smooth, but today we [encountered a 404](https://github.com/47ng/nuqs/pull/785#issuecomment-2531031126) when trying to install from the PR-numbered URL given by pkg.pr.new: 
```
https://pkg.pr.new/nuqs@785
```

Installing via the SHA-1 URL works:

```
https://pkg.pr.new/nuqs@d000ca8db65a027e11960c4b99736017c2a5ddaa
```

Timeline:
- The PR (47ng/nuqs#785) was opened and deployed for the first time 2 weeks ago (2024-11-28).
- The last [run](https://github.com/47ng/nuqs/actions/runs/12252630536/job/34179660721#step:8:1) to deploy via pkg.pr.new succeeded today (2024-12-10)

I see there were two runs triggered within one second of each other, one for approval, and one for synchronize (added a commit). Could it be a race condition causing this kind of issue?

![CleanShot 2024-12-10 at 10 58 51@2x](https://github.com/user-attachments/assets/81258a6b-18ed-4e51-adcd-411ef25a6661)

**Comment by Aslemammad** [comment]
ok, i'm sorry for the bad experience. see #289 

i think because it was merged the link to the pr got removed. we fixed this but we need a release soon! 

thank you so much for letting us know!

**Comment by franky47** [comment]
Ah that makes sense, I was wondering what the lifecycle of a preview deployment was (TIL about the 6 months TTL, it makes sense). Thanks!

**Comment by Aslemammad** [comment]
Thank you so much!
