### ISSUE TITLE
Keep previews active longer

### ISSUE THREAD

**Issue by theoephraim** [stackblitz-labs/pkg.pr.new#307]
Currently when PRs are closed, preview packages are immediately removed. If users are using preview packages in their dependencies, it means they now have a a broken build. Particularly when using changesets, sometimes there is a lag between PRs being merged and that code being published to npm, meaning a user may need to track down a new preview package url, which will then break again.

I propose we add a lag before deletion - could be user configurable, maybe default to 30 days?

**Comment by Aslemammad** [comment]
hey theo, thank you so much for creating the issue! with #289 and it being released, this should not happen anymore. 

let me know if it happened!

**Comment by theoephraim** [comment]
Ok awesome. I will try to verify.

**Comment by theoephraim** [comment]
Looks like everything is working as intended :)

**Comment by Aslemammad** [comment]
Thank you so much for closing!
