### ISSUE TITLE
Upload fails 

### ISSUE THREAD

**Issue by ematipico** [stackblitz-labs/pkg.pr.new#62]
Hi, 

I am trying to use the snippet provided by your examples, but it fails.

https://github.com/biomejs/biome/actions/runs/9205039486/job/25319850742

I believe the issue is the naming convention of scoped packages.

**Comment by Aslemammad** [comment]
we just released 0.0.5! Please let me know if it fixes the issue! feel free to close this one.

**Comment by ematipico** [comment]
It works, thank you!

**Comment by Aslemammad** [comment]
I appreciate that from you!
