### ISSUE TITLE
Extra spaces in the commands provided by the GitHub App

### ISSUE THREAD

**Issue by Sec-ant** [stackblitz-labs/pkg.pr.new#64]
Hello,

I noticed there're extra spaces at the end of the commands provided by the GitHub App bot. It's not a big deal, but I wonder if we can remove them?

![image](https://github.com/stackblitz-labs/pkg.pr.new/assets/10386119/eef2ed95-b1b0-4061-98c6-caa6d55bb27e)

**Comment by Aslemammad** [comment]
Niceeee, thank you so much for trying the app. Would you like to send a PR?

**Comment by Sec-ant** [comment]
> Niceeee, thank you so much for trying the app. Would you like to send a PR?

Sure, will do. I wasn't aware that the bot source is also hosted here.

**Comment by Aslemammad** [comment]
Yep! It is.
