### ISSUE TITLE
JSON.stringify breaks indentation

### ISSUE THREAD

**Issue by Aslemammad** [stackblitz-labs/pkg.pr.new#69]
When hijacking deps for templates support or workspace support! Since we stringify and parse, the indentation of the user's package json breaks and becomes like this:

```js
{"name":"example-1","version":"1.0.0","description":"","main":"index.js","scripts":{"test":"echo \"Error: no test specified\" && exit 1"},"keywords":[],"author":"","license":"ISC","dependencies":{"playground-a":"https://fc530866.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/playground-a@d51ad5a","playground-b":"https://fc530866.stackblitz-cr.pages.dev/stackblitz-labs/pkg.pr.new/playground-b@d51ad5a"}}
```

Is there any alternative? Maybe we can use Regex?

**Comment by Aslemammad** [comment]
Niceee, how would we edit the file without breaking indention?

**Comment by sadeghbarati** [comment]
`pkg-types` is using [`confbox`](https://github.com/unjs/confbox/blob/main/src/json.ts#L27) which will handle indention

**Comment by Aslemammad** [comment]
I just love that! Let me know if you'd like to send a PR for this.

**Comment by sadeghbarati** [comment]
> Continuous Releases are only available in Github Actions.

Since I can't test it locally show me a way to test and make a PR

**Comment by Aslemammad** [comment]
yea that makes sense, you can just open a pr and try pushing and logging 😄 so don't worry about the spam! would that be good?
