### ISSUE TITLE
Support pnpm and yarn for tarball creation

### ISSUE THREAD

**Issue by AmirSa12** [stackblitz-labs/pkg.pr.new#81]
adding options to support pnpm and yarn when creating a tarball.
for now, we are using npm by default.

**Comment by Aslemammad** [comment]
I have a potential solution for this, ill send a pr and you can continue the work on it.

**Comment by sadeghbarati** [comment]
@Aslemammad There is [`unjs/nypm`](https://github.com/unjs/nypm) to detect user packageManager and use detected one to create tarball file with
