### ISSUE TITLE
There is no workflow defined for ...

### ISSUE THREAD

**Issue by Sec-ant** [stackblitz-labs/pkg.pr.new#95]
Hello @Aslemammad,

We once disabled the `pkg-pr-new` publish job in the workflow and now we decide to add it back. But `pnpx pkg-pr-new publish` now gives us the `There is no workflow defined for ...` error. Is this a bug or are we using it in a wrong way?

The failed job: https://github.com/biomejs/biome/actions/runs/9389095954/job/25855841148#step:10:16

![image](https://github.com/stackblitz-labs/pkg.pr.new/assets/10386119/aa979b78-0652-4092-b715-8db2f129b533)

cc @ematipico

**Comment by Aslemammad** [comment]
Oh that's bad, on the vite pr we have the same issue, I'll try to find a way for this, thank you for the report! 

I'll try forking and debugging. Thanks.

**Comment by Aslemammad** [comment]
just fixed this, it helped me rethink a bit of the architecture, thank you so much again.

**Comment by Sec-ant** [comment]
> just fixed this, it helped me rethink a bit of the architecture, thank you so much again.

Cool! Huge thanks. I see the fix is related to #96, we should wait for it to merge, right?

**Comment by Aslemammad** [comment]
Yea yea, we'll have a release soon!

**Comment by Aslemammad** [comment]
just released 0.0.8!

**Comment by Timeless0911** [comment]
https://github.com/web-infra-dev/rslib/actions/runs/13406867187/job/37448281506?pr=765

![Image](https://github.com/user-attachments/assets/d4cdf60b-4954-44d6-a501-50e10fa8257f)

Hi, @Aslemammad, I still encountered this issue. At first I thought I needed to merge yml into the main branch, but now I still have this error. Could you pls help me address this issue? ❤️
