### ISSUE TITLE
pnpm has trouble parsing dependencies installed from pkg.pr.new

### ISSUE THREAD

**Issue by Sec-ant** [stackblitz-labs/pkg.pr.new#99]
Hello, @Aslemammad 

We use `pnpm` as our package manager to install one of the dependencies from `pkg.pr.new`. However, when we add other dependencies or run `pnpm outdated` or sometimes `pnpm i`, the following error will be printed.

```
pnpm: /@pkg.pr.new/biomejs/biome/@biomejs/wasm-web/74074fa is an invalid relative dependency path
```
This is reproducible in our netlify deployment logs.

The error log: https://app.netlify.com/sites/biomejs/deploys/666289860054490008562960#L49

I can also reproduce it locally, by running `pnpm outdated` for example after installing everything. And here is the repo: https://github.com/biomejs/website

I suspect this is a bug of `pnpm` because it also has trouble dealing with packages installed from CodeSandbox CI and there's an issue about it: https://github.com/pnpm/pnpm/issues/7698

Just want to let you know this problem and maybe you have better understanding on what might be causing this. And we appreciate it if there's a workaround without changing the package manager.

Thanks!

cc @ematipico

**Comment by Aslemammad** [comment]
Thank you so much for reproducing this! That's bad news, let me investigate it and I'll get back to you.

**Comment by ematipico** [comment]
I can also reproduce locally, but it occurs after installing a new dependency, hence the lock file is updated

**Comment by Sec-ant** [comment]
@Aslemammad 

We think this is caused by us using an old lock file version (`6.0`). We no longer see this issue after we updated our lock file version to `9.0`. I'll close this issue and sorry about the noise.

https://github.com/biomejs/website/pull/543#discussion_r1632028670

By the way, thank you for this great tool. It powers our crucial CI flow :)

**Comment by Aslemammad** [comment]
That's great news, happy y'all figured it out!
